alias gaa='git add *'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gph='git push'
alias gpl='git pull'
alias gd='git diff'
alias gs='git status'
alias gr='git rm'

